spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/test_db"
    username: postgres
    password: postgres
logging:
  level:
    org:
      hibernate:
        type: trace